# =====================================================================
# ImmuneML Galaxy deployment configuration
# =====================================================================

# ---------------------------------------------------------------------
# Target VM
# ---------------------------------------------------------------------
galaxy:
  host_ip: "use.real.host.ip"
  ssh_user: "SSH_USER"


# ---------------------------------------------------------------------
# Galaxy repository
# ---------------------------------------------------------------------
galaxy_repo: "https://github.com/galaxyproject/galaxy.git"
galaxy_commit_id: "release_26.0"
galaxy_force_checkout: true

# ---------------------------------------------------------------------
# Galaxy admin
# ---------------------------------------------------------------------
galaxy_admin_email: "admin@example.com"


# ---------------------------------------------------------------------
# Database secret
# ---------------------------------------------------------------------
galaxy_database_password: "CHANGE_ME_STRONG_PASSWORD"

## ---------------------------------------------------------------------
## Galaxy tool dependency resolver
## ---------------------------------------------------------------------
## Enables Galaxy-native Conda dependency handling for tool requirements.
#galaxy_enable_conda_dependencies: true

## ---------------------------------------------------------------------
## Https configurations
## ---------------------------------------------------------------------
galaxy_enable_https: true
galaxy_https_mode: "selfsigned"
galaxy_server_name: "galaxy.local"
galaxy_https_redirect: false
