---
# =====================================================================
# Sample of galaxy-role deployment playbook
# =====================================================================

- name: Deploy Galaxy using galaxy_deployment role
  hosts: galaxyservers
  become: true
  vars_files:
  - ../group_vars/galaxyservers.yml
  roles:
    - role: galaxy_deployment
