---
# =====================================================================
# Sample of galaxy-role deployment playbook
# =====================================================================

- name: Deploy Galaxy using galaxy_deployment role
  hosts: galaxyservers
  become: true

  roles:
    - role: galaxy_deployment
